import './globals.css';

import type { Metadata } from 'next';

import { Inter } from 'next/font/google';
import Providers from './providers';

import Header from './components/header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  modals,
  children,
}: Readonly<{
  modals: React.ReactNode;
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased flex flex-col w-full h-[calc(100dvh)] items-center justify-start`}
      >
        <Providers>
          <Header />

          {modals}

          {children}
        </Providers>
      </body>
    </html>
  );
}
